# Generated by Django 5.2.11 on 2026-03-24 17:50

import core.Models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationvacancy',
            options={'ordering': ('order_index', 'id')},
        ),
        migrations.AddField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='estimated_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='moderator_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationvacancy',
            name='line_salary_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.Models.vacancy_video_upload_to),
        ),
        migrations.AlterField(
            model_name='application',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('FORMED', 'Сформирована'), ('FINISHED', 'Завершена'), ('REJECTED', 'Отклонена'), ('DELETED', 'Удалена')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.application'),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_lines', to='core.vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.Models.vacancy_image_upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='applicationvacancy',
            unique_together={('application', 'vacancy')},
        ),
    ]
